#!/bin/sh
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://github.com/stedolan/jq/releases/download/jq-1.6/jq-1.6.tar.gz"
export ZOPEN_TARBALL_DEPS="make" 

zopen_check_results()
{
# Really simple check - make sure output log has the right line
#
dir="$1"
pfx="$2"
chk="$1/$2_check.log"

grep 'All tests passed' "${chk}"
}

